# Generated by Django 4.1.7 on 2023-03-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='a_username',
        ),
    ]
